<a href="https://colab.research.google.com/github/Areeba-Tariq/ML-AI/blob/main/DataPreprocessingTools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [5]:
import numpy as np  #for scientific computing
import matplotlib.pyplot as plt #for plotting
import pandas as pd #for importing the dataset,cleaning data

## Importing the dataset

In [6]:
dataset=pd.read_csv('sample_data/Data.csv') #making dataframe
x=dataset.iloc[:,:-1].values  #matrix of features x , iloc mean locate indices , : mean all rows in first argument , iloc[rows, columns]
# : means range it has upper n lower bound [it includes the upper bound
# but excludes the lower bound and -1 represent the index of last col so we are excluding last col]
y=dataset.iloc[:,-1].values #-1 is index of last col


In [7]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [9]:
from sklearn.impute import SimpleImputer #SimpleImputer is a class
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3]) #calculate the avg
x[:,1:3]=imputer.transform(x[:,1:3]) #not incluidng index 0 becoz cause error as that has strings , replces the missing data with calculated avg (during fit)

In [10]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [11]:
from sklearn.compose import ColumnTransformer # ColumnTransformer=Allows to apply transformations to specific columns in dataset
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(
    transformers=[('encorder',OneHotEncoder(),[0])]#  # 'encoder' applies OneHotEncoder[one hot encoded=binary] to column 0
    ,remainder='passthrough')#means keep the rest of cols unchanged
 #for transformers =kind of transformations e.g encorder, which kind of encoding and third is index of cols
X=np.array(ct.fit_transform(x)) #Apply the transformation and convert the result to a NumPy array

In [12]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [16]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [17]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [18]:
print(Y_train)


[0 1 0 0 1 1 0 1]


In [19]:
print(Y_test)

[0 1]


## Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler() #feature scaling is done on non dummy variables
X_train[:,3:]=sc.fit_transform(X_train[:,3:]) #fit compute the mean n standard deviation of each feature e.g mean of age
#transform apply the formula and transfrom ur cols
X_test[:,3:]=sc.transform(X_test[:,3:]) #transform method from same scalar

In [21]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [22]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
